### ISSUE TITLE
Java JVM configuration

### ISSUE THREAD

**Issue by archenroot** [famzah/langs-performance#8]
You should in minimum calculate heap and offheap space and configure it via Xms=Xmx=3G for example and also configure MetaSpace.

Additionally there is common set of JVM PRODUCTION grade configuration settings which affect performnce a lot.

Something like:
Java >= 8
    -server
    -Xms<heap size>[g|m|k] -Xmx<heap size>[g|m|k]
    -XX:MaxMetaspaceSize=<metaspace size>[g|m|k]
    -Xmn<young size>[g|m|k]
    -XX:SurvivorRatio=<ratio>
    -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled
    -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=<percent>
    -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark
    -XX:+PrintGCDateStamps -verbose:gc -XX:+PrintGCDetails -Xloggc:"<path to log>"
    -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M
    -Dsun.net.inetaddr.ttl=<TTL in seconds>
    -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=<path to dump>`date`.hprof
    -Djava.rmi.server.hostname=<external IP>
    -Dcom.sun.management.jmxremote.port=<port> 
    -Dcom.sun.management.jmxremote.authenticate=false 
    -Dcom.sun.management.jmxremote.ssl=false

Lastly, what is causing the delay in these synthetic tests usually is the JVM startup itself. I am curious about JVM preloaded into memory based results by using:
https://github.com/martylamb/nailgun

If you are not interested or don't have time to do this, I will as I think Java will win finally :-)

**Comment by famzah** [comment]
Hi, this has been discussed already. Hinting Java about the needed memory usage isn't fair. You can review the following: https://github.com/famzah/langs-performance/tree/master/java-optimizations

It's not the JVM startup delay which is being accounted here. The tests run for 90 wall-clock seconds and the startup time is a negligible part.

Feel free to do your own tests and to prove me wrong. But don't do any JVM optimizations which are tightly coupled with this task like memory/heap size and GC tuning.

**Comment by archenroot** [comment]
I understand the point. Unfortunately to me it isn't fair to NOT using JVM
config. The switches I refer to are standard set for any environment I work
with. When I install any app, I always apply this as default.

Anyway, thanks for answer and for project itself.

Ladislav

2017-06-06 6:46 GMT+02:00 Ivan Zahariev <notifications@github.com>:

**Comment by famzah** [comment]
If those config options are such a silver bullet for performance, why aren't they defaults for JVM?

**Comment by archenroot** [comment]
Well, each system is different and meant for different load, I like the idea to tune it for specific purpose. It is not big deal when you get in.

Anyway I think one of biggest improvement (out of JVM tuning) is to use non-builtin data structures to prevent unboxing/boxing as I see you described it in the tuning docs. I really wonder why those are not included in JDK class set.

Thanks for your work - similar to https://benchmarksgame.alioth.debian.org/ approach.

**Comment by archenroot** [comment]
To me JVM configuration as default is fine, I work with Gentoo, so GCC by default also don't surprise me a lot, but when I go on my Dell XPS 15 with:
```
CFLAGS="-march=skylake -mabm -maes -madx -mrtm"
CFLAGS="${CFLAGS} -mavx256-split-unaligned-load -mavx256-split-unaligned-store"
CFLAGS="${CFLAGS} --param l1-cache-line-size=64 --param l1-cache-size=32 --param l2-cache-size=6144"
CFLAGS="${CFLAGS} -O2 -pipe"
CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3"
CXXFLAGS="${CFLAGS}"
```
It is then different story, to me similar to JVM config options. I know looks like apples and oranges as different phases of optimization, but this is similarity from tuning place perspective only.

Thanks again, I am playing with your project for whole day already :-)))
